on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
     
    - name: 'Login via Azure CLI'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}
        enable-AzPSSession: true
        allow-no-subscriptions: true
    - name: 'Create env file'
      run: |
        echo "${{ secrets.ENV_FILE_DEPLOY_PROD }}" > .env
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER_PROD }}
        username: ${{ secrets.REGISTRY_USERNAME_PROD }}
        password: ${{ secrets.REGISTRY_PASSWORD_PROD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER_PROD }}/extracciontextos-prod:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER_PROD }}/extracciontextos-prod:${{ github.sha }}
    - name: 'Deploy in App Service'    
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'api-prod-tec-cognitive-extracciontextos'
        images: '${{ secrets.REGISTRY_LOGIN_SERVER_PROD }}/extracciontextos-prod:${{ github.sha }}'  
    - name: Azure logout
      run: |
        az logout
